language: android
android:
  components:
  	- tools
    - build-tools-19.1.0
    - android-19
    - platform-tools
    - extra

before_install:
 - chmod +x client_android/gradlew

before_script: cd client_android

script: "./gradlew build"