language: android
android:
  components:
    - build-tools-18.1.1
    - android-18
    - extra

jdk:
  - oraclejdk7
  - openjdk7

before_install:
 - chmod +x client_android/gradlew

before_script: cd client_android